/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/shared/Avatar.vue')['default']
    BottomNavigation: typeof import('./src/components/chat/BottomNavigation.vue')['default']
    ChatWindow: typeof import('./src/components/chat/chat-window/ChatWindow.vue')['default']
    ConversationList: typeof import('./src/components/chat/ConversationList.vue')['default']
    DialogCloseButton: typeof import('./src/components/shared/DialogCloseButton.vue')['default']
    DialogManager: typeof import('./src/components/shared/DialogManager.vue')['default']
    EmojiPickerButton: typeof import('./src/components/chat/chat-window/InputBlock/EmojiPickerButton.vue')['default']
    ImagePreviewDialog: typeof import('./src/components/chat/chat-window/ImagePreviewDialog.vue')['default']
    ImageUploadButton: typeof import('./src/components/chat/chat-window/InputBlock/ImageUploadButton.vue')['default']
    InputBlock: typeof import('./src/components/chat/chat-window/InputBlock/InputBlock.vue')['default']
    MessageBlock: typeof import('./src/components/chat/chat-window/MessageBlock/MessageBlock.vue')['default']
    MessageItem: typeof import('./src/components/chat/chat-window/MessageBlock/MessageItem/MessageItem.vue')['default']
    MoreOptionsButton: typeof import('./src/components/chat/chat-window/MessageBlock/MessageItem/MoreOptionsButton.vue')['default']
    NoticeDialog: typeof import('./src/components/shared/NoticeDialog.vue')['default']
    OtherMessageRecalled: typeof import('./src/components/chat/chat-window/MessageBlock/MessageItem/OtherMessageRecalled.vue')['default']
    OtherRepliedMessageImage: typeof import('./src/components/chat/chat-window/MessageBlock/MessageItem/OtherRepliedMessageImage.vue')['default']
    OtherRepliedMessageText: typeof import('./src/components/chat/chat-window/MessageBlock/MessageItem/OtherRepliedMessageText.vue')['default']
    OtherReplyContent: typeof import('./src/components/chat/chat-window/MessageBlock/MessageItem/OtherReplyContent.vue')['default']
    OwnMessageRecalled: typeof import('./src/components/chat/chat-window/MessageBlock/MessageItem/OwnMessageRecalled.vue')['default']
    OwnMessageStatus: typeof import('./src/components/chat/chat-window/MessageBlock/MessageItem/OwnMessageStatus.vue')['default']
    OwnRepliedMessageImage: typeof import('./src/components/chat/chat-window/MessageBlock/MessageItem/OwnRepliedMessageImage.vue')['default']
    OwnRepliedMessageText: typeof import('./src/components/chat/chat-window/MessageBlock/MessageItem/OwnRepliedMessageText.vue')['default']
    OwnReplyContent: typeof import('./src/components/chat/chat-window/MessageBlock/MessageItem/OwnReplyContent.vue')['default']
    RegisterDialog: typeof import('./src/components/login/RegisterDialog.vue')['default']
    ReplyPreview: typeof import('./src/components/chat/chat-window/InputBlock/ReplyPreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserStatus: typeof import('./src/components/chat/chat-window/UserStatus.vue')['default']
    UserStatusList: typeof import('./src/components/chat/UserStatusList.vue')['default']
  }
}
